# 練習問題解答 {#practiceanswer}


## Ch.4

**練習問題** \@ref(practicecalc)

```{r}
# 1
9179/67

# 2
(256*43+54)/8

# 3
1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 + 11 + 12

```

**練習問題** \@ref(practiceloop)

```{r}
# まずgoukeiに0を入れる
goukei <- 0

for(i in 1:50){
  goukei <- goukei + i
}

print(goukei)
```

**練習問題** \@ref(vectormake)

```{r}
# 3から60まで3ずつ増える数列
v7_ex <- seq(3,60,by=3)

print(v7_ex)

```

**練習問題** \@ref(#vectormake2)

```{r}
v9_ex <- rep(seq(2,10,by=2), 5)

# パイプを使って以下のように書くこともできる(パイプは第6章を参照)

v9_ex <- seq(2,10,by=2) |> rep(5)
  
```




## Ch. 6

**練習問題** \@ref{datamgtpractice}

1. 武蔵大学経済学部の学生数データを使って、女性のみの合計学生数を学年別で計算せよ。`data_634_long_1_2_grade`というオブジェクトに格納し、同様に結果を表示せよ。

```{r}
## 女性のみの学年ごとの学生数
data_634_long_female_grade <- data_634_long |>
  filter(性別=="女") |>
  group_by(学年) |>
  summarise(学生数合計 = sum(学生数))

print(data_634_long_female_grade)
```

2. 同じデータを使って、１,２年生のみ合計学生数を男女別・学年別で計算せよ。

```{r}
## 女性のみの学年ごとの学生数
data_634_long_1_2_grade <- data_634_long |>
  filter(学年=="1年" | 学年 == "2年") |> #数字が半角か、などに気をつける
  group_by(性別, 学年) |>  ## ２つのカテゴリでグループ分け
  summarise(学生数合計 = sum(学生数))

print(data_634_long_1_2_grade)
```

## Ch. 8

**練習問題**\@ref(scatterpractice)：散布図

```{r, fig.align='center', fig.height=4, fig.width=7.5}
plot_scatter <- ggplot(data=diamonds) + 
  geom_point(aes(x=carat,y=price, 
                 color=color))

print(plot_scatter)
```

**練習問題**\@ref(lineplotpractice)：折れ線グラフ

```{r}
plot_line <- ggplot(data=economics) + 
  geom_line(aes(x=date,y=unemploy))
```

```{r, fig.align='center', fig.height=5, fig.width=5}
print(plot_line)
```